-- CREATES THE SAFEDIV FUNCTION
DELIMITER //

CREATE FUNCTION SafeDiv(a INT, b INT)
RETURNS FLOAT
DETERMINISTIC
BEGIN
  -- IF B = 0 THEN IT RETURNS 0
  IF b = 0 THEN
    RETURN 0;
  ELSE
    RETURN a / b;
  END IF;
END //

DELIMITER ;